var statusLabels={lead:'Aday',in_progress:'Devam ediyor',completed:'Tamamlandı',cancelled:'İptal',refunded:'İade',partial_refund:'Kısmi iade',disputed:'İtiraz'};
function money(amount,currency){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency:currency}).format(amount)}catch(e){return esc(amount)+' '+esc(currency)}}
function safeLink(url,label){try{var u=new URL(url);if(u.protocol==='https:'&&(/(^|\.)(upwork\.com|gumroad\.com|fiverr\.com)$/.test(u.hostname)))return '<a class="btn" target="_blank" rel="noopener noreferrer" href="'+esc(u.href)+'">'+esc(label)+'</a>'}catch(e){}return ''}
function hubSummary(){var h=S.hub;return '<div class="grid"><div class="card"><span class="muted">Siparişler</span><div class="value">'+h.stats.orders+'</div></div><div class="card"><span class="muted">Aktif işler</span><div class="value">'+h.stats.active+'</div></div><div class="card"><span class="muted">Geciken teslim</span><div class="value">'+h.stats.overdue+'</div></div><div class="card"><span class="muted">Tamamlanan satış tutarı</span><div class="value" style="font-size:20px">'+(h.totals.map(function(t){return money(t.amount,t.currency)}).join('<br>')||money(0,'USD'))+'</div></div></div><p class="muted">Brüt tutar: komisyonlar düşülmez; test, iade, kısmi iade ve itirazlı satışlar toplama dahil değildir. Farklı para birimleri ayrı gösterilir.</p>'}
function channels(){var h='<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(240px,1fr))">';S.hub.channels.forEach(function(c){h+='<div class="card"><h2>'+esc(c.name)+'</h2><p>'+esc(c.state==='manual'?'Manuel takip':c.state==='connected'?(c.mode==='email'?'Gmail bağlı':'API bağlı'):c.state==='attention'?'Bağlantıyı kontrol edin':(c.mode==='email'?'Gmail bağlı değil':'API bağlı değil'))+'</p><p class="muted">'+esc(c.label)+'</p><p class="muted">'+(c.last_synced_at?'Son eşitleme: '+esc(new Date(c.last_synced_at).toLocaleString('tr-TR')):'Henüz veri eşitlenmedi.')+'</p>'+safeLink(c.url,'Platformu aç');if(c.mode==='email'){h+=fiverrMailCard()}else if(c.mode==='api'){h+=' <button class="btn" onclick="connectChannel(\''+c.platform+'\')">'+(c.connected?'Anahtarı güncelle':'API bağla')+'</button>';if(c.connected)h+=' <button class="btn" onclick="syncChannel(\''+c.platform+'\',this)">Şimdi eşitle</button> <button class="btn" onclick="disconnectChannel(\''+c.platform+'\')">Bağlantıyı kaldır</button>'}else h+='<p class="muted">Siparişinizi ekleyin veya standart CSV yükleyin.</p><button class="btn" onclick="newOrder(\'fiverr\')">Sipariş ekle</button>';h+='<p class="muted">'+esc(c.last_error)+'</p></div>'});h+='</div><div class="card section"><h3>Gumroad ürünleri</h3>';if(!S.products.length)h+='<p class="muted">Ürünleri görmek için Gumroad hesabınızı bağlayıp eşitleyin.</p>';S.products.forEach(function(p){h+='<div class="row"><div><b>'+esc(p.name)+'</b><p>'+money(p.price/100,p.currency)+' · '+(p.published?'Yayında':'Yayında değil')+'</p></div>'+safeLink(p.url,'Ürünü aç')+'</div>'});$('content').innerHTML=h+'</div>'}
function connectChannel(platform){var help=platform==='gumroad'?'Gumroad uygulamanızdan view_profile ve view_sales izinli erişim anahtarı kullanın.':'Onaylı Upwork geliştirici uygulamanızdan ilan okuma yetkili OAuth erişim anahtarı kullanın. Süresi dolan anahtarı burada yenileyin.';openModal('API bağlantısı','<p>'+help+'</p><p class="muted">Anahtar sunucuda şifrelenir. Tarayıcı girişiniz ayrı bir oturumdur.</p><form id="connectForm"><div class="field"><input id="channelToken" type="password" autocomplete="off" placeholder="Erişim anahtarı" required></div><button class="primary" type="submit">Doğrula ve bağla</button></form>');$('connectForm').onsubmit=async function(e){e.preventDefault();var b=e.submitter;b.disabled=true;try{await api('/api/channels/'+platform+'/connect',{method:'POST',body:JSON.stringify({token:$('channelToken').value.trim()})});$('channelToken').value='';closeModal();await load();toast('API bağlantısı doğrulandı')}catch(x){toast(x.message)}finally{b.disabled=false}}}
async function syncChannel(p,b){b.disabled=true;try{var r=await api('/api/channels/'+p+'/sync',{method:'POST'});await load();toast(r.processed+' kayıt eşitlendi'+(r.has_more?'; sonraki sayfa için yeniden eşitleyin.':'.'))}catch(e){toast(e.message);await load()}finally{b.disabled=false}}
async function disconnectChannel(p){if(!confirm('API bağlantısı kaldırılsın mı? Mevcut kayıtlar korunur.'))return;try{await api('/api/channels/'+p+'/connection',{method:'DELETE'});await load();toast('Bağlantı kaldırıldı')}catch(e){toast(e.message)}}
function orders(){var h=hubSummary()+'<div class="card"><button class="btn" onclick="newOrder()">Sipariş ekle</button> <button class="btn" onclick="importOrders()">CSV yükle</button> <a class="btn" href="/api/channel-orders/export">CSV indir</a><div class="field" style="margin-top:16px"><input id="orderSearch" placeholder="Başlık, müşteri veya sipariş numarası ara"><select id="orderPlatform"><option value="">Tüm platformlar</option><option>upwork</option><option>gumroad</option><option>fiverr</option></select></div><p class="muted">'+S.orders.length+' / '+S.orderTotal+' kayıt gösteriliyor.</p><div id="orderList"></div></div>';$('content').innerHTML=h;$('orderSearch').oninput=orderList;$('orderPlatform').onchange=orderList;orderList()}
function orderList(){var q=$('orderSearch').value.toLowerCase(),p=$('orderPlatform').value;var rows=S.orders.filter(function(o){return(!p||o.platform===p)&&[o.title,o.customer,o.external_id].join(' ').toLowerCase().includes(q)});$('orderList').innerHTML=rows.map(function(o){return '<div class="row"><div><b>'+esc(o.title)+'</b><p class="muted">'+esc(o.platform)+' · '+esc(o.external_id)+' · '+esc(o.customer)+'</p><p class="muted">'+esc(o.notes)+(o.due_date?' · Teslim: '+esc(o.due_date):'')+'</p><span class="tag">'+(o.source==='api'?'API':'Manuel')+(o.is_test?' · Test':'')+'</span></div><div><b>'+money(o.amount,o.currency)+'</b><p>'+esc(statusLabels[o.status]||o.status)+'</p>'+(o.source==='manual'?'<button class="btn" onclick="editOrder('+o.id+')">Düzenle</button>':'')+'</div></div>'}).join('')||'<p class="muted">Kayıt bulunamadı.</p>'}
function statusOptions(selected){return Object.keys(statusLabels).map(function(k){return '<option value="'+k+'" '+(k===selected?'selected':'')+'>'+statusLabels[k]+'</option>'}).join('')}
function newOrder(platform){openModal('Sipariş ekle','<form id="orderForm"><div class="field"><label>Platform</label><select id="op">'+['upwork','gumroad','fiverr'].map(function(p){return '<option '+(p===platform?'selected':'')+'>'+p+'</option>'}).join('')+'</select></div><div class="field"><input id="oi" placeholder="Platform sipariş numarası" required maxlength="200"></div><div class="field"><input id="ot" placeholder="İş / ürün adı" required maxlength="300"></div><div class="field"><input id="oc" placeholder="Müşteri (isteğe bağlı)" maxlength="200"></div><div class="field"><input id="oa" type="number" min="0" step="0.01" placeholder="Brüt tutar" required><input id="ou" value="USD" pattern="[A-Za-z]{3}" maxlength="3" aria-label="Para birimi"></div><div class="field"><select id="os">'+statusOptions('in_progress')+'</select><input id="od" type="date" aria-label="Teslim tarihi"></div><div class="field"><textarea id="on" placeholder="Notlar" maxlength="4000"></textarea></div><button class="primary">Kaydet</button></form>');$('orderForm').onsubmit=async function(e){e.preventDefault();try{await api('/api/channel-orders/import',{method:'POST',body:JSON.stringify({orders:[{platform:$('op').value,external_id:$('oi').value,title:$('ot').value,customer:$('oc').value,amount:$('oa').value,currency:$('ou').value,status:$('os').value,due_date:$('od').value,notes:$('on').value}]})});closeModal();await load();go('orders');toast('Sipariş kaydedildi')}catch(x){toast(x.message)}}}
function editOrder(id){var o=S.orders.find(function(r){return r.id===id});openModal('Siparişi güncelle','<form id="editForm"><div class="field"><select id="es">'+statusOptions(o.status)+'</select><input id="ed" type="date" value="'+esc(o.due_date||'')+'" aria-label="Teslim tarihi"></div><div class="field"><textarea id="en" maxlength="4000">'+esc(o.notes)+'</textarea></div><button class="primary">Kaydet</button></form>');$('editForm').onsubmit=async function(e){e.preventDefault();try{await api('/api/channel-orders/'+id,{method:'PATCH',body:JSON.stringify({status:$('es').value,due_date:$('ed').value,notes:$('en').value})});closeModal();await load()}catch(x){toast(x.message)}}}
function importOrders(){openModal('Standart CSV yükle','<p class="muted">Başlıklar: platform,external_id,title,customer,amount,currency,status,due_date,notes<br>Platform: upwork / gumroad / fiverr. Durum: lead / in_progress / completed / cancelled / refunded / partial_refund / disputed. Tarih: YYYY-MM-DD. En fazla 500 kayıt; aynı sipariş numarası manuel kaydı günceller.</p><input type="file" id="csvFile" accept=".csv,text/csv"><textarea id="csvText" style="width:100%;height:160px" placeholder="CSV içeriği"></textarea><button id="csvSave" class="primary">İçe aktar</button>');$('csvFile').onchange=async function(){if(this.files[0])$('csvText').value=await this.files[0].text()};$('csvSave').onclick=async function(){try{var r=await api('/api/channel-orders/import',{method:'POST',body:JSON.stringify({csv:$('csvText').value.replace(/^\uFEFF/,'')})});closeModal();await load();toast(r.processed+' kayıt aktarıldı')}catch(e){toast(e.message)}}}

function editProposal(id){var p=S.proposals.find(function(r){return r.id===id});openModal('Teklif taslağı','<form id="proposalForm"><div class="field"><textarea id="proposalBody" style="width:100%;min-height:260px" maxlength="20000" required>'+esc(p.body)+'</textarea></div><button class="primary">Taslağı kaydet</button></form><p class="muted">Metni inceleyip Upwork ilanındaki başvuru formuna aktarın.</p>'+safeLink(p.url,'Upwork üzerinde aç'));$('proposalForm').onsubmit=async function(e){e.preventDefault();try{await api('/api/proposals/'+id,{method:'PATCH',body:JSON.stringify({status:p.status,body:$('proposalBody').value})});closeModal();await load();toast('Taslak kaydedildi')}catch(x){toast(x.message)}}}

async function saveProfile(){try{await api('/api/profile',{method:'PUT',body:JSON.stringify({relevant_experience:$('experience').value.split('\n').filter(Boolean),proof:$('proof').value})});await load();toast('Profil kaydedildi')}catch(e){toast(e.message)}}

var mailKinds={message:'Mesajlar',order:'Siparişler',offer:'Teklifler',notification:'Bildirimler'};
function fiverrMailCard(){var m=S.fiverrMail;if(!m)return '';return '<p class="muted">Fiverr bildirim e-postaları Gmail üzerinden alınır. E-posta tutarları satış toplamına eklenmez.</p><button class="btn" onclick="connectFiverrMail()" '+(!m.ready?'disabled':'')+'>'+(m.connected?'Gmail hesabını değiştir':'Gmail ile bağla')+'</button> '+(m.connected?'<button class="btn" onclick="syncFiverrMail(this)">E-postaları eşitle</button> <button class="btn" onclick="disconnectFiverrMail()">Gmail bağlantısını kaldır</button>':'')+(!m.ready?'<p class="muted">Sunucuda Gmail OAuth yapılandırması bekleniyor.</p>':'')+'<p class="muted">Panel açıkken iki dakikada bir kontrol edilir. Son 90 gün taranır; her eşitleme en fazla 3 e-posta alır.</p><button class="btn" onclick="newOrder(\'fiverr\')">Sipariş ekle</button>'}
async function connectFiverrMail(){try{var r=await api('/api/fiverr-mail/connect',{method:'POST'});location.href=r.url}catch(e){toast(e.message)}}
async function syncFiverrMail(button){if(button)button.disabled=true;try{var r=await api('/api/fiverr-mail/sync',{method:'POST'});await load();toast(r.throttled?'Bir dakika sonra yeniden eşitleyin.':r.processed+' e-posta işlendi'+(r.has_more?'; geçmiş taraması sonraki eşitlemede devam edecek.':'.'))}catch(e){toast(e.message)}finally{if(button)button.disabled=false}}
async function disconnectFiverrMail(){if(!confirm('Gmail bağlantısı ve alınan e-posta kayıtları kaldırılsın mı?'))return;try{await api('/api/fiverr-mail/connection',{method:'DELETE'});await load()}catch(e){toast(e.message)}}
var originalChannels=channels;
channels=function(){originalChannels();var m=S.fiverrMail;if(!m)return;var box=document.createElement('div');box.className='card section';var h='<h3>Fiverr e-posta akışı</h3><p class="muted">Bildirim özeti; tam konuşma ve sipariş ayrıntıları Fiverr hesabınızda bulunur.</p>';
Object.keys(mailKinds).forEach(function(kind){h+='<h4>'+mailKinds[kind]+'</h4>';var rows=m.events.filter(function(e){return e.category===kind});h+=rows.map(function(e){return '<div class="row"><div><b>'+esc(e.subject)+'</b><p class="muted">'+esc(e.preview)+'</p><p class="muted">'+esc(e.sender)+' · '+esc(new Date(e.occurred_at).toLocaleString('tr-TR'))+(e.unread?' · Gmail’de okunmamış':'')+'</p></div>'+safeLink('https://www.fiverr.com/inbox','Fiverr aç')+'</div>'}).join('')||'<p class="muted">Kayıt yok.</p>'});box.innerHTML=h;$('content').appendChild(box)};
var gmailResult=new URLSearchParams(location.search).get('gmail_result');
if(gmailResult){history.replaceState(null,'',location.pathname);setTimeout(function(){toast(gmailResult==='connected'?'Gmail bağlandı. Platformlar bölümünden e-postaları eşitleyin.':gmailResult==='cancelled'?'Gmail bağlantısı iptal edildi.':'Gmail bağlanamadı. Google yapılandırmasını ve izinleri kontrol edin.')},500)}
var mailPolling=false;
setInterval(async function(){if(mailPolling||document.hidden||!S.user||!S.fiverrMail||!S.fiverrMail.connected)return;mailPolling=true;try{await api('/api/fiverr-mail/sync',{method:'POST'});await load()}catch(e){}finally{mailPolling=false}},120000);
